title: Sangria
description: "Sangria - Scala GraphQL Implementation"
baseurl: ""
url: "http://sangria-graphql.org"
bootstrap-theme: flatly
ga-code: UA-65759630-1
domain: sangria-graphql.org

version:
  sangria: 1.3.3
  sangria-relay: 1.3.3
  sangria-spray-json: 1.0.0
  sangria-play-json: 1.0.4
  sangria-json4s-native: 1.0.0
  sangria-json4s-jackson: 1.0.0
  sangria-circe: 1.1.0
  sangria-msgpack: 1.0.0
  sangria-ion: 1.0.0
  sangria-argonaut: 1.0.0
  sangria-marshalling-api: 1.0.0
  sangria-marshalling-testkit: 1.0.1
  sangria-streaming-api: 1.0.0
  sangria-akka-streams: 1.0.0
  sangria-rxscala: 1.0.0
  sangria-monix: 1.0.0
  sangria-slowlog: 0.1.4
  macro-visit: 0.1.1

groupId: org.sangria-graphql

link:
  sangria-github: https://github.com/sangria-graphql
  sangria-maven: http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.sangria-graphql%22
  twitter: https://twitter.com/easyangel
  stack-overflow: http://stackoverflow.com/questions/tagged/sangria
  stack-overflow-ask: http://stackoverflow.com/questions/ask?tags=scala,graphql,sangria
  google-groups: https://groups.google.com/forum/#!forum/sangria-graphql
  sangria-changelog: https://github.com/sangria-graphql/sangria/blob/master/CHANGELOG.md
  repo:
    sangria: https://github.com/sangria-graphql/sangria
    sangria-relay: https://github.com/sangria-graphql/sangria-relay
    sangria-spray-json: https://github.com/sangria-graphql/sangria-spray-json
    sangria-play-json: https://github.com/sangria-graphql/sangria-play-json
    sangria-json4s-native: https://github.com/sangria-graphql/sangria-json4s-native
    sangria-json4s-jackson: https://github.com/sangria-graphql/sangria-json4s-jackson
    sangria-circe: https://github.com/sangria-graphql/sangria-circe
    sangria-msgpack: https://github.com/sangria-graphql/sangria-msgpack
    sangria-ion: https://github.com/sangria-graphql/sangria-ion
    sangria-argonaut: https://github.com/sangria-graphql/sangria-argonaut
    sangria-marshalling-api: https://github.com/sangria-graphql/sangria-marshalling-api
    sangria-marshalling-testkit: https://github.com/sangria-graphql/sangria-marshalling-testkit
    sangria-streaming-api: https://github.com/sangria-graphql/sangria-streaming-api
    sangria-akka-streams: https://github.com/sangria-graphql/sangria-akka-streams
    sangria-rxscala: https://github.com/sangria-graphql/sangria-rxscala
    sangria-monix: https://github.com/sangria-graphql/sangria-monix
    sangria-slowlog: https://github.com/sangria-graphql/sangria-slowlog
    macro-visit: https://github.com/sangria-graphql/macro-visit
  maven:
    sangria: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria_
    sangria-relay: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-relay_
    sangria-spray-json: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-spray-json_
    sangria-play-json: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-play-json_
    sangria-json4s-native: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-json4s-native_
    sangria-json4s-jackson: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-json4s-jackson_
    sangria-circe: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-circe_
    sangria-msgpack: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-msgpack_
    sangria-ion: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-ion_
    sangria-argonaut: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-argonaut_
    sangria-marshalling-api: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-marshalling-api_
    sangria-marshalling-testkit: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-marshalling-testkit_
    sangria-streaming-api: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-streaming-api_
    sangria-akka-streams: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-akka-streams_
    sangria-rxscala: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-rxscala_
    sangria-monix: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-monix_
    sangria-slowlog: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Csangria-slowlog_
    macro-visit: http://search.maven.org/#artifactdetails%7Corg.sangria-graphql%7Cmacro-visit_
  issues:
    sangria: https://github.com/sangria-graphql/sangria/issues
    sangria-relay: https://github.com/sangria-graphql/sangria-relay/issues
    sangria-spray-json: https://github.com/sangria-graphql/sangria-spray-json/issues
    sangria-play-json: https://github.com/sangria-graphql/sangria-play-json/issues
    sangria-json4s-native: https://github.com/sangria-graphql/sangria-json4s-native/issues
    sangria-json4s-jackson: https://github.com/sangria-graphql/sangria-json4s-jackson/issues
    sangria-circe: https://github.com/sangria-graphql/sangria-circe/issues
    sangria-msgpack: https://github.com/sangria-graphql/sangria-msgpack/issues
    sangria-ion: https://github.com/sangria-graphql/sangria-ion/issues
    sangria-argonaut: https://github.com/sangria-graphql/sangria-argonaut/issues
    sangria-marshalling-api: https://github.com/sangria-graphql/sangria-marshalling-api/issues
    sangria-marshalling-testkit: https://github.com/sangria-graphql/sangria-marshalling-testkit/issues
    sangria-streaming-api: https://github.com/sangria-graphql/sangria-streaming-api/issues
    sangria-akka-streams: https://github.com/sangria-graphql/sangria-akka-streams/issues
    sangria-rxscala: https://github.com/sangria-graphql/sangria-rxscala/issues
    sangria-monix: https://github.com/sangria-graphql/sangria-monix/issues
    sangria-slowlog: https://github.com/sangria-graphql/sangria-slowlog/issues
    macro-visit: https://github.com/sangria-graphql/macro-visit/issues
  releases:
    sangria: https://github.com/sangria-graphql/sangria/releases
    sangria-relay: https://github.com/sangria-graphql/sangria-relay/releases
    sangria-spray-json: https://github.com/sangria-graphql/sangria-spray-json/releases
    sangria-play-json: https://github.com/sangria-graphql/sangria-play-json/releases
    sangria-json4s-native: https://github.com/sangria-graphql/sangria-json4s-native/releases
    sangria-json4s-jackson: https://github.com/sangria-graphql/sangria-json4s-jackson/releases
    sangria-circe: https://github.com/sangria-graphql/sangria-circe/releases
    sangria-msgpack: https://github.com/sangria-graphql/sangria-msgpack/releases
    sangria-ion: https://github.com/sangria-graphql/sangria-ion/releases
    sangria-argonaut: https://github.com/sangria-graphql/sangria-argonaut/releases
    sangria-marshalling-api: https://github.com/sangria-graphql/sangria-marshalling-api/releases
    sangria-marshalling-testkit: https://github.com/sangria-graphql/sangria-marshalling-testkit/releases
    sangria-streaming-api: https://github.com/sangria-graphql/sangria-streaming-api/releases
    sangria-akka-streams: https://github.com/sangria-graphql/sangria-akka-streams/releases
    sangria-rxscala: https://github.com/sangria-graphql/sangria-rxscala/releases
    sangria-slowlog: https://github.com/sangria-graphql/sangria-slowlog/releases
    macro-visit: https://github.com/sangria-graphql/macro-visit/releases
  website: https://github.com/sangria-graphql/sangria-website
  jekyll: http://jekyllrb.com/
  ghpages: https://pages.github.com/
  graphql: http://facebook.github.io/graphql/
  akka-http-example:
    github: https://github.com/sangria-graphql/sangria-akka-http-example
    activator: https://www.typesafe.com/activator/template/sangria-akka-http-example
  try: http://try.sangria-graphql.org
  toolbox: http://toolbox.sangria-graphql.org
  try-relay: http://try-relay.sangria-graphql.org
  spec:
    errors: https://facebook.github.io/graphql/#sec-Errors

markdown: kramdown
permalink: pretty
highlighter: rouge

gems:
- jekyll-redirect-from
- jekyll-sitemap
